<?php
/**
 * Arabic Translation Script for Aureus ERP
 * This script translates English strings to Arabic in PHP language files
 */

// Common translations dictionary
$translations = [
    // Navigation & UI
    'Navigation' => 'التنقل',
    'Configurations' => 'الإعدادات',
    'Settings' => 'الإعدادات',
    'Dashboard' => 'لوحة التحكم',
    'Overview' => 'نظرة عامة',
    'Reports' => 'التقارير',
    'Reporting' => 'التقارير',
    'Management' => 'الإدارة',
    
    // Common Terms
    'Name' => 'الاسم',
    'Title' => 'العنوان',
    'Description' => 'الوصف',
    'Status' => 'الحالة',
    'Active' => 'نشط',
    'Inactive' => 'غير نشط',
    'Archived' => 'مؤرشف',
    'All' => 'الكل',
    'Color' => 'اللون',
    'Code' => 'الرمز',
    'Type' => 'النوع',
    'Date' => 'التاريخ',
    'Notes' => 'ملاحظات',
    'Note' => 'ملاحظة',
    
    // Actions
    'Create' => 'إنشاء',
    'Edit' => 'تعديل',
    'Update' => 'تحديث',
    'Delete' => 'حذف',
    'Save' => 'حفظ',
    'Cancel' => 'إلغاء',
    'Confirm' => 'تأكيد',
    'Submit' => 'إرسال',
    'Send' => 'إرسال',
    'Restore' => 'استعادة',
    'View' => 'عرض',
    'Preview' => 'معاينة',
    'Add' => 'إضافة',
    'Remove' => 'إزالة',
    'Search' => 'بحث',
    'Filter' => 'تصفية',
    'Sort' => 'ترتيب',
    'Export' => 'تصدير',
    'Import' => 'استيراد',
    'Download' => 'تنزيل',
    'Upload' => 'رفع',
    'Print' => 'طباعة',
    'Lock' => 'قفل',
    'Unlock' => 'إلغاء القفل',
    
    // Business Terms
    'Company' => 'الشركة',
    'Companies' => 'الشركات',
    'Customer' => 'العميل',
    'Customers' => 'العملاء',
    'Vendor' => 'المورد',
    'Vendors' => 'الموردين',
    'Partner' => 'الشريك',
    'Partners' => 'الشركاء',
    'Contact' => 'جهة الاتصال',
    'Contacts' => 'جهات الاتصال',
    'Employee' => 'الموظف',
    'Employees' => 'الموظفين',
    'User' => 'المستخدم',
    'Users' => 'المستخدمين',
    'Team' => 'الفريق',
    'Teams' => 'الفرق',
    'Department' => 'القسم',
    'Departments' => 'الأقسام',
    'Manager' => 'المدير',
    'Leader' => 'القائد',
    
    // Sales & Orders
    'Sales' => 'المبيعات',
    'Order' => 'الطلب',
    'Orders' => 'الطلبات',
    'Quotation' => 'عرض السعر',
    'Quotations' => 'عروض الأسعار',
    'Invoice' => 'الفاتورة',
    'Invoices' => 'الفواتير',
    'Bill' => 'فاتورة المورد',
    'Bills' => 'فواتير الموردين',
    'Payment' => 'الدفع',
    'Payments' => 'المدفوعات',
    'Credit Note' => 'إشعار دائن',
    'Credit Notes' => 'إشعارات دائنة',
    'Refund' => 'استرداد',
    
    // Products & Inventory
    'Product' => 'المنتج',
    'Products' => 'المنتجات',
    'Category' => 'الفئة',
    'Categories' => 'الفئات',
    'Quantity' => 'الكمية',
    'Price' => 'السعر',
    'Unit Price' => 'سعر الوحدة',
    'Unit' => 'الوحدة',
    'UOM' => 'وحدة القياس',
    'Unit Of Measure' => 'وحدة القياس',
    'Stock' => 'المخزون',
    'Inventory' => 'المخزون',
    'Warehouse' => 'المستودع',
    'Location' => 'الموقع',
    'Packaging' => 'التغليف',
    
    // Financial
    'Amount' => 'المبلغ',
    'Total' => 'الإجمالي',
    'Sub Total' => 'المجموع الفرعي',
    'Subtotal' => 'المجموع الفرعي',
    'Tax' => 'الضريبة',
    'Taxes' => 'الضرائب',
    'Discount' => 'الخصم',
    'Currency' => 'العملة',
    'Account' => 'الحساب',
    'Accounts' => 'الحسابات',
    'Journal' => 'دفتر اليومية',
    'Journals' => 'دفاتر اليومية',
    'Bank' => 'البنك',
    'Banks' => 'البنوك',
    'Bank Account' => 'الحساب البنكي',
    'Bank Accounts' => 'الحسابات البنكية',
    'Cost' => 'التكلفة',
    'Margin' => 'الهامش',
    'Profit' => 'الربح',
    'Loss' => 'الخسارة',
    
    // Dates & Time
    'Created At' => 'تاريخ الإنشاء',
    'Updated At' => 'تاريخ التحديث',
    'Deleted At' => 'تاريخ الحذف',
    'Created By' => 'أنشئ بواسطة',
    'Created by' => 'أنشئ بواسطة',
    'Due Date' => 'تاريخ الاستحقاق',
    'Start Date' => 'تاريخ البداية',
    'End Date' => 'تاريخ النهاية',
    'Expiration' => 'تاريخ الانتهاء',
    'Delivery Date' => 'تاريخ التسليم',
    
    // Form & Table
    'Form' => 'نموذج',
    'Table' => 'جدول',
    'Fields' => 'الحقول',
    'Columns' => 'الأعمدة',
    'Filters' => 'التصفيات',
    'Groups' => 'المجموعات',
    'Actions' => 'الإجراءات',
    'General' => 'عام',
    'General Information' => 'معلومات عامة',
    'Other Information' => 'معلومات أخرى',
    'Additional Information' => 'معلومات إضافية',
    'Section' => 'قسم',
    
    // Address
    'Address' => 'العنوان',
    'City' => 'المدينة',
    'State' => 'المنطقة',
    'Country' => 'البلد',
    'Zip' => 'الرمز البريدي',
    'Street' => 'الشارع',
    'Phone' => 'الهاتف',
    'Email' => 'البريد الإلكتروني',
    'Mobile' => 'الجوال',
    'Fax' => 'الفاكس',
    'Website' => 'الموقع الإلكتروني',
    
    // Notifications
    'created' => 'تم الإنشاء',
    'updated' => 'تم التحديث',
    'deleted' => 'تم الحذف',
    'restored' => 'تم الاستعادة',
    'successfully' => 'بنجاح',
    'The' => '',
    'has been' => 'تم',
    
    // Projects
    'Project' => 'المشروع',
    'Projects' => 'المشاريع',
    'Task' => 'المهمة',
    'Tasks' => 'المهام',
    'Activity' => 'النشاط',
    'Activities' => 'الأنشطة',
    'Milestone' => 'المرحلة',
    'Deadline' => 'الموعد النهائي',
    'Priority' => 'الأولوية',
    'Progress' => 'التقدم',
    
    // HR
    'Leave' => 'إجازة',
    'Time Off' => 'إجازة',
    'Attendance' => 'الحضور',
    'Timesheet' => 'سجل الوقت',
    'Timesheets' => 'سجلات الوقت',
    'Recruitment' => 'التوظيف',
    'Job' => 'الوظيفة',
    'Jobs' => 'الوظائف',
    'Applicant' => 'المتقدم',
    'Applicants' => 'المتقدمين',
    'Application' => 'طلب التوظيف',
    'Applications' => 'طلبات التوظيف',
    'Interview' => 'مقابلة',
    'Salary' => 'الراتب',
    'Contract' => 'العقد',
    
    // Purchases
    'Purchase' => 'المشتريات',
    'Purchases' => 'المشتريات',
    'Purchase Order' => 'أمر الشراء',
    'Purchase Orders' => 'أوامر الشراء',
    'Request for Quotation' => 'طلب عرض سعر',
    'Supplier' => 'المورد',
    'Suppliers' => 'الموردين',
    
    // Shipping
    'Shipping' => 'الشحن',
    'Delivery' => 'التسليم',
    'Tracking' => 'التتبع',
    'Carrier' => 'الناقل',
    
    // Others
    'Tag' => 'الوسم',
    'Tags' => 'الوسوم',
    'Label' => 'التسمية',
    'Labels' => 'التسميات',
    'Image' => 'الصورة',
    'Images' => 'الصور',
    'Attachment' => 'المرفق',
    'Attachments' => 'المرفقات',
    'File' => 'الملف',
    'Files' => 'الملفات',
    'Document' => 'المستند',
    'Documents' => 'المستندات',
    'Comment' => 'تعليق',
    'Comments' => 'التعليقات',
    'Message' => 'رسالة',
    'Messages' => 'الرسائل',
    
    // Phrases
    'Terms & Conditions' => 'الشروط والأحكام',
    'Term & Conditions' => 'الشروط والأحكام',
    'Terms and Conditions' => 'الشروط والأحكام',
    'Payment Term' => 'شروط الدفع',
    'Payment Terms' => 'شروط الدفع',
    'Sales Person' => 'مندوب المبيعات',
    'Sales Team' => 'فريق المبيعات',
    'Sales Teams' => 'فرق المبيعات',
    'Customer Reference' => 'مرجع العميل',
    'Source Document' => 'المستند المصدر',
    'Order Line' => 'بنود الطلب',
    'Invoice Line' => 'بنود الفاتورة',
    'Invoice Lines' => 'بنود الفاتورة',
    'Add Product' => 'إضافة منتج',
    'New' => 'جديد',
    
    // States
    'Draft' => 'مسودة',
    'Confirmed' => 'مؤكد',
    'Done' => 'منجز',
    'Cancelled' => 'ملغى',
    'Pending' => 'قيد الانتظار',
    'In Progress' => 'قيد التنفيذ',
    'Completed' => 'مكتمل',
    'Approved' => 'موافق عليه',
    'Rejected' => 'مرفوض',
    'Sent' => 'مُرسل',
    'Received' => 'مستلم',
    'Paid' => 'مدفوع',
    'Partial' => 'جزئي',
    'Full' => 'كامل',
    'Open' => 'مفتوح',
    'Closed' => 'مغلق',
    
    // Misc
    'Yes' => 'نعم',
    'No' => 'لا',
    'True' => 'صحيح',
    'False' => 'خطأ',
    'None' => 'لا شيء',
    'Other' => 'أخرى',
    'Default' => 'افتراضي',
    'Custom' => 'مخصص',
    'Required' => 'مطلوب',
    'Optional' => 'اختياري',
];

echo "Arabic Translation Script for Aureus ERP\n";
echo "========================================\n";
echo "Translation dictionary contains " . count($translations) . " entries.\n";
echo "Use this dictionary for consistent translations.\n";
