<livewire:chatter-panel
    :record="$record"
    :resource-class="$resourceClass"
    :follower-view-mail-path="$followerMailViewPath"
    :is-follower-action-visible="$isFileActionVisible"
    :is-file-action-visible="$isFollowerActionVisible"
    :activity-plans="$activityPlans"
    lazy
/>